backend: tensorflow
class_name: Sequential
config:
  layers:
  - class_name: InputLayer
    config:
      batch_input_shape: !!python/tuple
      - null
      - 1
      - 3
      dtype: float32
      name: conv1d_11_input
      ragged: false
      sparse: false
  - class_name: Conv1D
    config:
      activation: relu
      activity_regularizer: null
      batch_input_shape: !!python/tuple
      - null
      - 1
      - 3
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      data_format: channels_last
      dilation_rate: !!python/tuple
      - 1
      dtype: float32
      filters: 64
      groups: 1
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          seed: null
      kernel_regularizer: null
      kernel_size: !!python/tuple
      - 3
      name: conv1d_11
      padding: same
      strides: !!python/tuple
      - 1
      trainable: true
      use_bias: true
  - class_name: MaxPooling1D
    config:
      data_format: channels_last
      dtype: float32
      name: max_pooling1d_11
      padding: valid
      pool_size: !!python/tuple
      - 1
      strides: !!python/tuple
      - 1
      trainable: true
  - class_name: Flatten
    config:
      data_format: channels_last
      dtype: float32
      name: flatten_11
      trainable: true
  - class_name: RepeatVector
    config:
      dtype: float32
      n: 3
      name: repeat_vector_11
      trainable: true
  - class_name: LSTM
    config:
      activation: tanh
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      dropout: 0.0
      dtype: float32
      go_backwards: false
      implementation: 2
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          seed: null
      kernel_regularizer: null
      name: lstm_23
      recurrent_activation: sigmoid
      recurrent_constraint: null
      recurrent_dropout: 0.0
      recurrent_initializer:
        class_name: Orthogonal
        config:
          gain: 1.0
          seed: null
      recurrent_regularizer: null
      return_sequences: false
      return_state: false
      stateful: false
      time_major: false
      trainable: true
      unit_forget_bias: true
      units: 200
      unroll: false
      use_bias: true
  - class_name: Dense
    config:
      activation: linear
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      dtype: float32
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          seed: null
      kernel_regularizer: null
      name: dense_51
      trainable: true
      units: 2
      use_bias: true
  name: sequential_31
keras_version: 2.4.0
